### ISSUE TITLE
remove or fix dist/bundle.js.map

### ISSUE THREAD

**Issue by wmathes** [crazyfactory/ts-http-client#14]
There's no need for a broken/empty .js.map within the bundle. Remove or fix this.

Note: Since the map file won't get published to npm because of .npmignore anyway it's not a problem to just remove it. It may though be useful during development for debugging so i would prefer a fix :)

**Comment by cyberhck** [comment]
IMO, we do a .gitignore, and let it be on development machine, it gives me nice mapping on my browser when I try to debug :)

**Comment by wmathes** [comment]
@cyberhck It would do that, IF it wasn't broken. :p That's why i asked for fix or remove ^^

**Comment by wmathes** [comment]
Fixed by #29
