### ISSUE TITLE
clean up dependencies

### ISSUE THREAD

**Issue by wmathes** [crazyfactory/ts-http-client#18]
Some of the dependencies are not used anymore. Some are outdated and some are deprecated.

Let's check which one's we can remove/update/exchange to get this project as up-to-date as possible before calling it 1.0.0 :)

**Comment by wmathes** [comment]
I think
````
"live-server": "^0.9.0",
"tsd": "^0.6.5",
```
are candidates for removal. Live-server is still listed in some places, but not really used anymore.

**Comment by cyberhck** [comment]
Are we starting with 1.0.0? I thought we start from 0.1.0 and follow the scheme which @Solomonic mentioned. bug fixes and minor patches the right most one, feature addition the left one and breaking changes the first one.

**Comment by wmathes** [comment]
the first ever release should always be a 1.0.0. This would mark our first real release :) 

after that i could imagine us using SemVer to handle future versioning completely by its own. Alternatively we'll do it by hand using github tags.

**Comment by wmathes** [comment]
As @cyberhck  mentioned in #27 we should remove the polyfill dependency to es6-promise as well and add it via typings instead since it's considered to be standard in ES6 and, if at all, browsers should be catered by the app not an underlying package.

This would also remove our last non-dev dependency :)
