### ISSUE TITLE
rename the package/repo/project?

### ISSUE THREAD

**Issue by wmathes** [crazyfactory/ts-http-client#23]
I'm a bit unhappy with the name of the project and the resulting packages. Maybe it's clever to address this now before we publish anything and start using it in other projects.

Currently we have two main classes. One is defining the basic functionality (HttpClient) and one that will use that functionality to gracefully provide access to API backends.

The following approach is currently forming in my head, though i'd be happy for additional input or alternatives :) @cyberhck @Solomonic @z3niths 

The idea of this is to focus on the packages main usage as an Api Access package.

## Proposal
1) rename HttpClient to FetchClient 
This would better reflect the actual purpose. 

2) rename HttpApiClient to ServiceClient
Shorter and more to the point. The inheritance to FetchClient doesn't need to be reflected necessarily.

3) rename the package to "cf-service-client" 
Since ServiceClient is the most used class in the package and the main reason the underlying class (and the whole package) exists, it should be namegiver of the package.

4) rename the repo to "ts-cf-service-client"
Change the repo name accordingly. Prefix with "ts-" to avoid future conflict's with api-client implementations for PHP/Go/.Net. 

## Notes:

1) Deriving packages would then be named "<project>-service-client" or just "<project>-service" and reside in prefixed Repos as well.

**Comment by cyberhck** [comment]
I liked the idea of having FetchClient, your previous name for HttpApiClient was better IMO, ApiClient gives a idea that it deals with API, No comments on any other of them :)

**Comment by wmathes** [comment]
alternatively... we can just rename HttpApiClient to ApiClient, though i think the term service is more standardized

**Comment by wmathes** [comment]
Alternatively i'm open for giving it a cute name... Something that resembles a dog, clever animal/contraption or butler may be fitting. Something that is not yet used as a package. :) 

Suggestions? @cyberhck @Solomonic @dacgray

**Comment by dacgray** [comment]
I suggest calling it request-beast

**Comment by wmathes** [comment]
How about "Tinka"? It's package name is unclaimed at npmjs. And it's the short version of Tinkabelle basically a friendly fairy catering to your needs :p 

Also it's on of the most popular golden retriever names of 2016 ^^

**Comment by wmathes** [comment]
We might add two more classes to the mix to help deriving Service Packages: 
- `Service` 
- `ServiceNode`

These two classes will have a minimal implementation [like this](https://gist.github.com/wmathes/bd0317709ebf982c2eb6fd215c409540) and will be the main classes used in service packages.

Renaming the other classes to be in line.
- `FetchClient`
- `ServiceClient`

Usage in for instance a Shop Service package would be [like this](https://gist.github.com/wmathes/215c5cb17793867c24a24d538876a897)

So in total it would come down to this:

**package**
- name: `@crazy-factory/service*` (private)

**classes**
- `FetchClient`
- `FetchClientConfiguration`
- `FetchClientResponse`
- `ServiceClient` extends `FetchClient`
- `Service
- `ServiceNode`

**interfaces**
- `IFetchClientRequestOptions`
- `IFetchClientMiddleware`
- `IServiceClientRequestOptions`

PS: We can turn the package public under a different name once it's somewhat stable. This isn't necessarily related to the sources though, but it's a start ^^

**Comment by dacgray** [comment]
yup, Great!

I'm working on it now, so I'll make the name changes.

**Comment by wmathes** [comment]
Most of this is handled in #43. 

Decided to just implement a single `Service`-class, instead of two. [It's very simple](https://github.com/crazyfactory/ts-http-client/blob/5837545377d88f50286382e2aa046d3ff3fcf9b8/src/lib/Service.ts) and will just return sub instances of itself if needed.

Package name is for now unchanged until we're happy with the result :)
