### ISSUE TITLE
Consider using bluebird instead of es6-promise

### ISSUE THREAD

**Issue by dacgray** [crazyfactory/ts-http-client#27]
Bluebird has a bigger community, great documentation, and more stars :)

[Bluebird Github](https://github.com/petkaantonov/bluebird)

**Comment by cyberhck** [comment]
Actually now to think about it, we don't really need es6-promise at all, those two are pollyfills, and will be injected if browser doesn't have one, I was actually supposed to only use typings, instead of the whole project. @wmathes , can you weigh in here? What do you think?

**Comment by wmathes** [comment]
I asked myself the same already but havent had the time to look into it yet. But yes.. it should be just a polyfill and therefor the responsibility of the app actually using the package and not of the package itself. Similar to the fetch polyfill.

**Comment by wmathes** [comment]
@dacgray You can probably change the issue to "replace es6-promise dependency with typings"

**Comment by wmathes** [comment]
On further thought... just do it as part of #18 :)
