### ISSUE TITLE
coverage doesn't honor sourcemaps

### ISSUE THREAD

**Issue by wmathes** [crazyfactory/ts-http-client#48]
Even though the sourcemaps generated in `/build/src` seem to be correct, there is an issue of the Coverage not being reported correctly by karma/istanbul.

The coverage itself is correctly determined, but the mapping back to the *.ts files is broken, resulting in the coverage being displayed/mapped to the original *.js files in the build folder. While this is already helpful it would be a lot nicer to see the actual coverage on the *.ts files again.

Lucky guess: The sourceRoot property might not be honored. This can be fixed in many ways and i'm not sure yet which one would be the best fit. There's remap-istanbul and alternatively karma-typescript, which might remove our last necessity on jspm as well.

PS: This broke when updating gulp-typescript and many other plugins that we cant afford to loose, so the old way might just not work anymore...

Up for grabs

**Comment by dacgray** [comment]
I looked into karma-typescript, and swapping out the test transpilation pipeline with browserify.  Although tests ran, and it generated coverage, the original problem remained.

**Comment by cyberhck** [comment]
I looked into karma-remap-istanbul and remap-istanbul, even though they can produce correct coverage on original TypeScript files, they don't return the result to "karma-coverage".

My findings:
- on `preprocessors`, element `sourcemap` doesn't have any effect what so ever in case of both inline source maps or external source map file.
- I can get TypeScript code coverage using `karma-remap-istanbul`, but this doesn't return the results back to coverage so we can't see results on our IDE, but we can see in external HTML file which it creates.

No luck. Not sure what's happening here.

**Comment by wmathes** [comment]
Today i had a look at the karma typescript preprocessor. It seemed to work like a charm, but in the end JSPM didn't play nicely. We could combine this with browserify maybe. 

I'll try out the jspm transpiler again soonishly...

**Comment by wmathes** [comment]
This has been solved by #54 

Full IntelliJ integration will resolve itself with this https://youtrack.jetbrains.com/oauth?state=%2Fissue%2FWEB-10303
