### ISSUE TITLE
Codecov.io not working

### ISSUE THREAD

**Issue by cyberhck** [crazyfactory/ts-http-client#52]
At second to the last step of travis build, we're sending coverage report to codecov.io which isn't working.

When we visit codecov.io, we don't see any coverage report properly, there's a browser extension from codecov.io which can overlay coverage right on github. Right now it's not doing anything. It's definitely a nice feature.

**Comment by wmathes** [comment]
I had a look into it and tried it out. In reality it's just a tiny badge for the repository, which currently isn't really worth the effort. 

At least the priority is super low for now.

The parts of the code that feature codecov is a fragment of my testing. Sorry :p
